"""Refresh bundled upstream metadata: uv run python scripts/update_upstream_metadata.py."""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from app.core.clients.codex_version import CodexVersionCache  # noqa: E402
from app.core.metadata_store import write_metadata  # noqa: E402
from app.core.types import JsonValue  # noqa: E402
from app.core.usage.pricing_catalog import (  # noqa: E402
    BUNDLE_PATH,
    LITELLM_URL,
    MAX_CATALOG_BYTES,
    MODELS_DEV_URL,
    decode_snapshot,
    encode_snapshot,
    merge_catalogs,
    parse_litellm,
    parse_models_dev,
)


def fetch(url: str) -> JsonValue:
    request = Request(url, headers={"User-Agent": "codex-lb", "Accept": "application/json"})
    with urlopen(request, timeout=30) as response:
        body = response.read(MAX_CATALOG_BYTES + 1)
        if len(body) > MAX_CATALOG_BYTES:
            raise ValueError("Pricing response too large")
        return json.loads(body)


async def main() -> None:
    # Generation requires both sources; never commit a degraded/partial snapshot.
    primary = parse_models_dev(await asyncio.to_thread(fetch, MODELS_DEV_URL))
    secondary = parse_litellm(await asyncio.to_thread(fetch, LITELLM_URL))
    prices = merge_catalogs(primary, secondary)
    version = await CodexVersionCache()._fetch_latest_version()
    if version is None:
        raise RuntimeError("No stable Codex release found")
    previous = json.loads(BUNDLE_PATH.read_text()) if BUNDLE_PATH.exists() else None
    if previous is not None:
        prices = merge_catalogs(prices, decode_snapshot(previous))
    content = encode_snapshot(prices)
    if previous is None or "updated_at" not in previous or decode_snapshot(previous) != prices:
        write_metadata(BUNDLE_PATH, content)
    write_metadata(
        ROOT / "app/core/clients/codex_version_snapshot.py",
        f'# Generated by scripts/update_upstream_metadata.py; do not edit manually.\nCODEX_VERSION = "{version}"\n',
    )
    print(f"Updated {len(prices)} model prices and Codex {version}")


if __name__ == "__main__":
    asyncio.run(main())
